title: Your awesome title
timezone: UTC
collections:
  lots:
    output: true
  people:
    output: true
  catalogues:
    output: true
email: your-email@example.com
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: ''
url: ''
twitter_username: jekyllrb
github_username: jekyll
sass:
  sass_dir: _sass
  style: compressed
cloudinary_url: "https://res.cloudinary.com/dcryyrd42/image/upload"


# Pagination Settings
pagination:
  enabled: true
  debug: true
  collection: lots
  per_page: 10
  permalink: '/page/:num/'
  limit: 0
  sort_field: 'LOT'



plugins:
  - jekyll-gzip
gems:
  - jekyll-paginate-v2