title: Your awesome title
timezone: UTC
collections:
  lots:
    output: true
    permalink: /:title
  people:
    output: true
email: your-email@example.com
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: ''
url: ''
twitter_username: jekyllrb
github_username: jekyll
sass:
  sass_dir: _sass
cloudinary_url: "https://res.cloudinary.com/dcryyrd42/image/upload"
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "lots"
    values:
      author: "Scott Gallant"